name: tests
on:
  push:
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
env:
  DOTNET_VERSION: '6.0.x'
jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dotnet-version: ['3.0','5.0.x','6.0' ]
    steps:
    - uses: actions/checkout@v3
    - name:  Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install app dependencies
      run: dotnet restore src
    - name: Install test dependencies
      run: dotnet restore tests
    - name: Build
      run: dotnet build src --configuration Release --no-restore
    - name: Test
      run: dotnet test tests --no-restore --verbosity normal
